// // Import the original ApiClient generated by NSwag
// import { ApiClient } from './client';  // שנה את הנתיב בהתאם למיקום של הקובץ שנוצר על ידי NSwag

// // יצירת קלאס שמרחיב את ApiClient
// export class AuthorizedApiClient extends ApiClient {
//     private getAuthorization: () => string;

//     constructor(baseUrl: string, getAuthorization: () => string) {
//         super(baseUrl);
//         this.getAuthorization = getAuthorization;
//     }

//     // Override של הפונקציה שמטפלת בהוספת Authorization לכל קריאה
//     protected transformOptions(options: RequestInit): Promise<RequestInit> {
//         if (this.getAuthorization()) {
//             options.headers = {
//                 ...options.headers,
//                 Authorization: `Bearer ${this.getAuthorization()}`,  // הוספת ה-Bearer Token
//             };
//         }
//         return super.transformOptions(options);
//     }
// }
